project_id = "xibihgkkubkcjdibysni"

[functions.confirm-email]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.financial-analytics]
verify_jwt = false

[functions.driver-location]
verify_jwt = false
