project_id = "xibihgkkubkcjdibysni"

[functions.create-user]
enabled = true
verify_jwt = false

[functions.confirm-email]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.get-vapid-key]
verify_jwt = false

[functions.financial-analytics]
verify_jwt = false

[functions.driver-location]
verify_jwt = false
